/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamplesIndexRouteImport } from './routes/examples/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ExamplesExampleRouteRouteImport } from './routes/examples/$example/route'
import { Route as ExamplesExampleIndexRouteImport } from './routes/examples/$example/index'
import { Route as LlmsDotmdxDocsSplatRouteImport } from './routes/llms[.]mdx.docs.$'
import { Route as ExamplesSrcExampleIdRouteImport } from './routes/examples/src/$exampleId'

const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesIndexRoute = ExamplesIndexRouteImport.update({
  id: '/examples/',
  path: '/examples/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesExampleRouteRoute = ExamplesExampleRouteRouteImport.update({
  id: '/examples/$example',
  path: '/examples/$example',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesExampleIndexRoute = ExamplesExampleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamplesExampleRouteRoute,
} as any)
const LlmsDotmdxDocsSplatRoute = LlmsDotmdxDocsSplatRouteImport.update({
  id: '/llms.mdx/docs/$',
  path: '/llms.mdx/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesSrcExampleIdRoute = ExamplesSrcExampleIdRouteImport.update({
  id: '/examples/src/$exampleId',
  path: '/examples/src/$exampleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/examples/$example': typeof ExamplesExampleRouteRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/examples/': typeof ExamplesIndexRoute
  '/examples/src/$exampleId': typeof ExamplesSrcExampleIdRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/examples/$example/': typeof ExamplesExampleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/examples': typeof ExamplesIndexRoute
  '/examples/src/$exampleId': typeof ExamplesSrcExampleIdRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/examples/$example': typeof ExamplesExampleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/examples/$example': typeof ExamplesExampleRouteRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/examples/': typeof ExamplesIndexRoute
  '/examples/src/$exampleId': typeof ExamplesSrcExampleIdRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/examples/$example/': typeof ExamplesExampleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/examples/$example'
    | '/api/search'
    | '/docs/$'
    | '/examples/'
    | '/examples/src/$exampleId'
    | '/llms.mdx/docs/$'
    | '/examples/$example/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/search'
    | '/docs/$'
    | '/examples'
    | '/examples/src/$exampleId'
    | '/llms.mdx/docs/$'
    | '/examples/$example'
  id:
    | '__root__'
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/examples/$example'
    | '/api/search'
    | '/docs/$'
    | '/examples/'
    | '/examples/src/$exampleId'
    | '/llms.mdx/docs/$'
    | '/examples/$example/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ExamplesExampleRouteRoute: typeof ExamplesExampleRouteRouteWithChildren
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  ExamplesIndexRoute: typeof ExamplesIndexRoute
  ExamplesSrcExampleIdRoute: typeof ExamplesSrcExampleIdRoute
  LlmsDotmdxDocsSplatRoute: typeof LlmsDotmdxDocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/': {
      id: '/examples/'
      path: '/examples'
      fullPath: '/examples/'
      preLoaderRoute: typeof ExamplesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/$example': {
      id: '/examples/$example'
      path: '/examples/$example'
      fullPath: '/examples/$example'
      preLoaderRoute: typeof ExamplesExampleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/$example/': {
      id: '/examples/$example/'
      path: '/'
      fullPath: '/examples/$example/'
      preLoaderRoute: typeof ExamplesExampleIndexRouteImport
      parentRoute: typeof ExamplesExampleRouteRoute
    }
    '/llms.mdx/docs/$': {
      id: '/llms.mdx/docs/$'
      path: '/llms.mdx/docs/$'
      fullPath: '/llms.mdx/docs/$'
      preLoaderRoute: typeof LlmsDotmdxDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/src/$exampleId': {
      id: '/examples/src/$exampleId'
      path: '/examples/src/$exampleId'
      fullPath: '/examples/src/$exampleId'
      preLoaderRoute: typeof ExamplesSrcExampleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExamplesExampleRouteRouteChildren {
  ExamplesExampleIndexRoute: typeof ExamplesExampleIndexRoute
}

const ExamplesExampleRouteRouteChildren: ExamplesExampleRouteRouteChildren = {
  ExamplesExampleIndexRoute: ExamplesExampleIndexRoute,
}

const ExamplesExampleRouteRouteWithChildren =
  ExamplesExampleRouteRoute._addFileChildren(ExamplesExampleRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ExamplesExampleRouteRoute: ExamplesExampleRouteRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  ExamplesIndexRoute: ExamplesIndexRoute,
  ExamplesSrcExampleIdRoute: ExamplesSrcExampleIdRoute,
  LlmsDotmdxDocsSplatRoute: LlmsDotmdxDocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
